# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torch', '0004_auto_20171109_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='casual_num',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='reference_num',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='toga_num',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='affiliations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torch.Course'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='eligibility',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='scholarships',
            field=models.TextField(blank=True, null=True),
        ),
    ]
