# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torch', '0005_auto_20171110_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='casual_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='reference_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='toga_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
