# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torch', '0006_auto_20171110_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
